import Link from 'next/link';

const Page = () => {
    return (
        <div className="flex">
            <div className='flex'>
                <div className="w-[200px] bg-gray-100 h-screen sticky top-[80px]">
                    <ul className="mt-4">
                        <li className="mb-4">
                            <Link href="/reports/sales">
                                <div className="text-blue-500 hover:text-blue-700">Sales Report</div>
                            </Link>
                        </li>
                        <li className="mb-4">
                            <Link href="/reports/expenses">
                                <div className="text-blue-500 hover:text-blue-700">Expenses Report</div>
                            </Link>
                        </li>
                        <li className="mb-4">
                            <Link href="/reports/profits">
                                <div className="text-blue-500 hover:text-blue-700">Profits Report</div>
                            </Link>
                        </li>
                    </ul>
                </div>
                <div className="w-[200px] bg-gray-100 h-screen sticky top-[80px]">
                    <ul className="mt-4">
                        <li className="mb-4">
                            <Link href="/reports/sales">
                                <div className="text-blue-500 hover:text-blue-700">Sales Report</div>
                            </Link>
                        </li>
                        <li className="mb-4">
                            <Link href="/reports/expenses">
                                <div className="text-blue-500 hover:text-blue-700">Expenses Report</div>
                            </Link>
                        </li>
                        <li className="mb-4">
                            <Link href="/reports/profits">
                                <div className="text-blue-500 hover:text-blue-700">Profits Report</div>
                            </Link>
                        </li>
                    </ul>
                </div>
            </div>

            <div className="w-3/4 bg-white p-8">
                <h1 className="text-3xl font-bold mb-8">Sales Report</h1>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget felis sed purus aliquet molestie. Nullam hendrerit sagittis eros, ac congue tellus fringilla sed. Nam dictum euismod arcu quis facilisis. Duis ac tellus eget felis tempor aliquet. Vivamus ac feugiat felis. Praesent non odio non lectus viverra pharetra nec vitae nisl. Fusce elementum libero vel metus tincidunt euismod.</p>
            </div>
        </div>
    );
};

export default Page;
